
create  table QUOTE_USER_ASSIGNMENT(
    USER_ID VARCHAR2(40) Primary key,
    PROPERTY_NAME  VARCHAR2(100), 
    TOKEN VARCHAR2(100), 
	ROLE_NAME VARCHAR2(100),
    RECORD_ADD_USER VARCHAR2(10), 
	RECORD_ADD_DATE DATE, 
	RECORD_CHANGE_USER VARCHAR2(10), 
    RECORD_CHANGE_DATE DATE

);




create  table QUOTE_USER_ASSIGNMENT_ROLE(
    USER_ID_FK VARCHAR2(40),
    PROPERTY_NAME  VARCHAR2(100), 
    RECORD_ADD_USER VARCHAR2(10), 
	RECORD_ADD_DATE DATE, 
	RECORD_CHANGE_USER VARCHAR2(10), 
    RECORD_CHANGE_DATE DATE,
    CONSTRAINT QUOTE_USER_ASSIGNMENT_ROLE_FK
    FOREIGN KEY (USER_ID_FK)
    REFERENCES QUOTE_USER_ASSIGNMENT(USER_ID)

);



 
create  table QUOTE_REQUEST(
    QUOTE_REQUEST_PK NUMBER(10) Primary key,
    POL  VARCHAR2(50), 
    POD  VARCHAR2(50), 
    SHIPPER  VARCHAR2(100), 
    VESSEL  VARCHAR2(50), 
    VOYOGE VARCHAR2(50), 
    VOLUME  VARCHAR2(50), 
    FREE_TIME  VARCHAR2(50), 
    TARGET_RATE  VARCHAR2(50), 
    TARGET_ETD  DATE,
    REQUEST_ID  VARCHAR2(50),
    APPROVE_ID  VARCHAR2(50),    
    APPOVE_BY  VARCHAR2(50),  
    REJECTED_BY  VARCHAR2(50),  
    REMARKS VARCHAR2(1000),
    CMODITY  VARCHAR2(250), 
    WEIGHT  VARCHAR2(150),     
    RECORD_ADD_USER VARCHAR2(10),
    RECORD_STATUS VARCHAR2(10), 
	RECORD_ADD_DATE DATE, 
	RECORD_CHANGE_USER VARCHAR2(10), 
    RECORD_CHANGE_DATE DATE
    );
    
    ALTER TABLE QUOTE_REQUEST ADD  REASON_OF_REJECT VARCHAR2(2000);
    
    //added on 20-12-2020
    ALTER TABLE QUOTE_REQUEST ADD  CONTRACT_PARTY VARCHAR2(50);

    

 