 
 

CREATE OR REPLACE FORCE EDITIONABLE VIEW "VASAPPS"."V_QUOTE_CAM_CUSTOMER"
(CUSTOMER_CODE,CUSTOMER_NAME,FSC) as
select PK_CUSTOMER_CODE,CUSTOMER_NAME ,FK_FSC FROM RCLTBLS.CAM_CUSTOMER  WHERE record_status = 'A' ;