
CREATE OR REPLACE FORCE EDITIONABLE VIEW "VASAPPS"."V_QUOTE_ESM_USER"
(USER_ID,USER_NAME,EMAIL_ID1,COMPANY_NAME,COUNTRY,PHONE,RECORD_STATUS) as

select USER_ID,USER_NAME,EMAIL_ID1,COMPANY_NAME,COUNTRY,PHONE,RECORD_STATUS from RCLTBLS.ESM_USER_LOGIN ;



 